### PR TITLE
various fixes and add e2e upgrades tests

### LINKED ISSUE #86: e2e upgrade tests
Currently our e2e tests are leveraging API-kind of tests, but with no real node attached. This prevents us to test things like upgrades, or specific scenarios where we inject custom node configuration.

This card is about to set-up in parallel a VM or something which mocks a os2 node and can join e2e tests for a simple upgrade scenario that can also be run locally while iterating during development.

### PR DESCRIPTION
**Pull request by mudler**
Fixes: https://github.com/rancher-sandbox/os2/issues/86
Part of https://github.com/rancher-sandbox/os2/issues/87 as includes custom syncer tests. Currently the suite imports a channel and tries to trigger an upgrade for it. It inspects the plan and that a pod which will run the upgrade starts in the cluster.

It includes also fixes found while doing tests which pushed multiple times the same env in the pod spec,  https://github.com/rancher-sandbox/rancheros-operator/pull/28/commits/903ccf6cfe11dabf7ba57d3bf9f6aa6ac959f340

### CODE REVIEW

**Comment by mudler** [comment]
Seems to be flaky at the moment as If I run them individually they work, but in sequence they don't as some pods trying to apply upgrades are still dangling and can't clean them up. gotta have a closer look :eyes: 

Besides, wanted to add a test that actually triggers on os2 releases to have a tentative run by checking up logs

**Comment by mudler** [comment]
Tests seems to be passing now and all should be good to go. Will move later over the suite also to os2 or either the discovery-channel repository so we can still use it to gate our changes.

File: tests/e2e/upgrades_test.go [hunk 1]
```diff
@@ -0,0 +1,396 @@
...
+
+	"github.com/rancher-sandbox/rancheros-operator/tests/catalog"
+)
+
+const cattleNamespace = "cattle-system"
+const fleetNamespace = "fleet-local"
+const discoveryPluginImage = "quay.io/costoolkit/upgradechannel-discovery:v0.3-4b83dbe"
+
+func getPlan(s string) (up *upgradev1.Plan, err error) {
+	up = &upgradev1.Plan{}
```
Comment (mudler) [inline tests/e2e/upgrades_test.go:40]: I've created https://github.com/rancher-sandbox/ele-testhelpers/pull/3 to refactor those common funcs, once merged I'll consume them here

Comment (mudler) [reply tests/e2e/upgrades_test.go:40]: done

**Review by davidcassany — APPROVED** [review]
Looks good, finally some upgrade test :+1:
